### PR TITLE
Add switch groups function

### LINKED ISSUE #1: Backend Task: Create function for users to switch groups
Estimated Effort: 3 days 

Dependencies: None 

Acceptance Criteria: Tests that show users can switch between different groups they're in as the current group

### PR DESCRIPTION
**Pull request by 0simoo**
Added switch function to src/groups/switch.js
This function basically just combines Groups.leave and Groups.join to switch a Group a user is in to another one
Added a test for switch to test/groups.js line 606

This merge also contains the translations for src/topics/merge.js from js to ts.

Resolves #1

### CODE REVIEW

**Comment by kian-nick** [comment]
LGTM! Let's fix linting errors later

**Review by kian-nick — APPROVED** [review]
LGTM! Let's address listing errors l8r

**Comment by Jiatonglii22** [comment]
looks good to me!

**Review by Jiatonglii22 — APPROVED** [review]
we can merge when ready

**Review by carolinemichalow — APPROVED** [review]
src/groups/switch.js looks great

src/merge.ts also looks great, few errors in the .js file. Test file also looks good!

**Pull request merged**
