### PR TITLE
Adds bare groundwork for students' answer features to come

### LINKED ISSUE #9: Backend Task: create a students' answer field for topics
Estimated Effort: 2-3 days

Dependencies: None

Acceptance Criteria: making sure linter and tests pass/typechecking functions

### PR DESCRIPTION
**Pull request by kian-nick**
Resolves #9 

Added relevant type additions and default values in files related to topics

### CODE REVIEW

**Review by 0simoo — APPROVED** [review]
There's some minor linting issues but those seem to be pretty trivial fixes.
Looks good to me!

**Comment by Jiatonglii22** [comment]
looks good to me!

**Review by Jiatonglii22 — COMMENTED** [review]
looks good to me!

**Review by carolinemichalow — APPROVED** [review]
looks good!

**Review by 0simoo — CHANGES_REQUESTED** [review]
Linter issues should be fixed before merging

**Review by 0simoo — APPROVED** [review]

**Comment by Jiatonglii22** [comment]
Looks good to me!

**Pull request merged**
